use_frameworks!

platform :ios, '8.0'

target 'JJCollectionViewRoundFlowLayout_Example' do
  pod 'JJCollectionViewRoundFlowLayout', :path => '../'
  pod 'IGListKit', '~> 2.1.0'
  
  target 'JJCollectionViewRoundFlowLayout_Tests' do
    inherit! :search_paths

    
  end
end
